### ISSUE TITLE
Unable to set prompt type (i.e select_account)

### ISSUE THREAD

**Issue by williamjulianvicary** [BingAds/BingAds-PHP-SDK#130]
To allow users to select an account to login with, rather than attempt to login with the current session it would be ideal if the API offered the capability to define the prompt type (and a login hint where appropriate).

I can't see any reference to prompt type here:
https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-identity-platform?view=bingads-13

However it seems some endpoints do support this:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow

Is this something that can be enabled for the Bing Ads API?

**Comment by javiernunez** [comment]
I've been wondering about this as well, I didn't find a solution yet to let the user choose the customer he wants to link, when he is already logged in with any.

**Comment by williamjulianvicary** [comment]
FWIW - I just appended `&prompt=select_account` to the endpoint and as expected I was asked to select the account. So it seems this is supported (at least unintentionally) but undocumented and not supported in the SDK.

**Comment by javiernunez** [comment]
> FWIW - I just appended `&prompt=select_account` to the endpoint and as expected I was asked to select the account. So it seems this is supported (at least unintentionally) but undocumented and not supported in the SDK.

Good to know! I will do the same. Thanks for the tip!

**Comment by eric-urban** [comment]
@williamjulianvicary @javiernunez thanks for flagging this issue! The prompt param is supported by design, and mentioned here in the [Microsoft Identity endpoint documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code). We'll add the same details to [Bing Ads API OAuth docs](https://docs.microsoft.com/en-us/advertising/guides/authentication-oauth-identity-platform?view=bingads-13#request-userconsent). The SDK provides GetAuthorizationEndpoint(), and clients can append the prompt as needed per user.

**Comment by eric-urban** [comment]
@williamjulianvicary @javiernunez the documentation has been updated. Thanks again.
