### ISSUE TITLE
 Image  Ad Extension

### ISSUE THREAD

**Issue by asmagillani** [BingAds/BingAds-PHP-SDK#3]
Please write a sample for image ad extension i tried but not able to create display ads

**Comment by eric-urban** [comment]
Please confirm are you interested in image ad extensions for [Native Ads](https://msdn.microsoft.com/en-us/library/bing-ads-native-ads.aspx)?

**Comment by asmagillani** [comment]
Yes i am interested Thanks

**Comment by eric-urban** [comment]
I do apologize for the delay. In the meantime there is a [.NET example](https://github.com/BingAds/BingAds-dotNet-SDK/blob/master/examples/BingAdsExamples/BingAdsExamplesLibrary/v11/AdExtensions.cs#L191) so you can see the high level workflow. Is there a specific error you are hitting when running your sample? 

You'll first need to add media, and then use the media ID for the image ad extension. While the minimum required for an image ad extension is one image, in order to qualify for all native ad placements you must provide four images, where each Image corresponds to one of the four supported [Media ](https://msdn.microsoft.com/library/dn195580.aspx) types (aspect ratios). The supported aspect ratios for native ads are 16:9, 1.5:1, 4:3, and 1.2:1. For more details please see the [Native Ads](https://msdn.microsoft.com/en-us/library/bing-ads-native-ads(v=msads.100).aspx#campaignservice) guide.
